//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Election.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidatesStatistic
    {
        public int Id { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public int NumberOfVoters { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
