//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoterInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Serial { get; set; }
        public string SubCommitteeNumber { get; set; }
        public string GeneralCommittee { get; set; }
        public string School { get; set; }
        public string Village { get; set; }
        public string Center { get; set; }
        public bool IsAttent { get; set; }
        public Nullable<int> AttendBy { get; set; }
        public string Farm { get; set; }
    
        public virtual User User { get; set; }
    }
}
